---
- name: Extract Downloaded Node Exporter
  unarchive:
    src: "{{ node_exporter }}"
    dest: /tmp/
    remote_src: yes

- name: grupp
  group: name=node_exporter
  become: true

- name: användare
  user:
    name: node_exporter
    group: node_exporter
    system: yes
    shell: "/sbin/nologin"
    comment: "node_exporter nologin User"
    createhome: "no"
    state: present

- name: Copy binary to /usr/local/bin
  copy:
    src: /tmp/node_exporter-0.18.1.linux-amd64/node_exporter
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: "0755"
    remote_src: yes

- name: Copy service to /etc/systemd/system
  template:
    src: config/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Reload daemon
  action: shell sudo systemctl daemon-reload

- name: Start service httpd, if not started
  service:
    name: node_exporter
    state: started
    enabled: yes






