---
-   name: Install aptitude
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

-   name: Install system
    apt: name={{item}} state=latest update_cache=yes
    loop: [
      'apt-transport-https',
      'ca-certificates',
      'curl',
      'software-properties-common',
      'python3-pip',
      'virtualenv',
      'python3-setuptools',
      'python-docker']

-   name: Add Docker GPG Key
    apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

-   name: Add Docker Repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present

-   name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest