version: '3'
services:
  test:
    container_name: microblog_test
    environment:
      FLASK_ENV: test
      FLASK_APP: microblog.py
    build:
      context: .
      dockerfile: docker/Dockerfile_test
    volumes:
      - ./test-data:/var/lib/test


  prod:
    container_name: microblog_prod
    environment:
      FLASK_APP: microblog.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://microblog:hemligt@db/microblog
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    links:
      - mysql:db
    restart: always
    ports:
      - "5000:5000"

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: hemligt
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql