---
- name: Pull Docker Image - statsd-exporter
  docker_image:
    name: prom/statsd-exporter
    source: pull

- name: Copy statsd_exporter to /home/deploy/
  template:
    src: ./config/statsd.conf
    dest: "{{ path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Run Docker Image statsd-exporter with statsd.conf
  command: docker run -dP --net=host -v "{{ path }}"statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
