# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: 8ptk4/microblog_prod
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    machine: true
    working_directory: ~/repo
    environment:
      FLASK_ENV: test
      FLASK_APP: microblog.py
    steps:
      - checkout
      - run:
          name: run docker tests
          command: make test
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image   
          command: docker build -t $IMAGE_NAME:latest -f ./docker/Dockerfile_prod .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  ansible-playbook:
    executor: docker-publisher

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Ansible 
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            make install-deploy
      - run:
          name: Execute Ansible playbook
          command: |
            . ../venv/bin/activate
            ansible-playbook gather_vm_instances.yml docker_container_application.yml
          working_directory: ansible

workflows:
  version: 2
  build-master:
    jobs:
      - test:
        filters:
          branches:
            only: master
      - docker/hadolint:
            name: hadolint
            ignore-rules: DL3019,DL3018
            dockerfiles: ./docker/Dockerfile_prod:./docker/Dockerfile_test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - ansible-playbook:
          requires:
            - publish-latest
          filters:
            branches:
              only: master

