---
region: northeurope
resource_group: BTH-kmom01-PAKA17-d47901
domain_name: puttekarlsson.xyz

root_user: azureuser

vmtags:
    StudentId: "paka17"

pub_ssh_key_location: '/home/patrik/.ssh/azureci.pub'