---
- name: Check if grafana_package is installed
  command: dpkg-query -W grafana_package
  register: grafana_package_check_deb
  failed_when: grafana_package_check_deb.rc > 1
  changed_when: grafana_package_check_deb.rc == 1

- name: Download grafana_package
  get_url: 
    url="{{ grafana_package_url }}"
    dest="/tmp/{{ grafana_package_name }}.deb"
  when: grafana_package_check_deb.rc == 1

- name: Install grafana_package
  apt: deb="/tmp/{{ grafana_package_name }}.deb"
  when: grafana_package_check_deb.rc == 1

- name: Start service grafana, if not started
  service:
    name: grafana-server
    state: started




