FROM python:3.6-alpine

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements requirements
COPY Makefile Makefile
COPY .pylintrc .pylintrc
COPY pytest.ini pytest.ini
COPY tests tests
COPY app app

RUN python -m venv venv
RUN apk --no-cache add --virtual build-dependencies=~20201108.070132 libffi-dev=~3.3-r2 openssl-dev=~1.1.1g-r0 make=~4.3-r0 python3-dev=3.8.5-r0 build-base=~0.5-r2 \
    && venv/bin/pip install --upgrade pip \
    && venv/bin/pip install -r requirements/test.txt 
RUN venv/bin/pip install gunicorn
RUN venv/bin/pip install gunicorn pymysql
RUN make install-test

COPY docker/test.sh .
RUN chmod +x test.sh

ENTRYPOINT ["./test.sh"]