FROM python:3.6-alpine

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements requirements
COPY Makefile Makefile
COPY .pylintrc .pylintrc
COPY pytest.ini pytest.ini
COPY tests tests
COPY app app

RUN python -m venv venv
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev make python3-dev py-pip build-base \
    && venv/bin/pip install --upgrade pip \
    && venv/bin/pip install -r requirements/test.txt 
RUN venv/bin/pip install gunicorn
RUN venv/bin/pip install gunicorn pymysql
RUN make install-test

COPY docker/test.sh .
RUN chmod +x test.sh

ENTRYPOINT ["./test.sh"]