
FROM python:3.6-alpine

RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements requirements

RUN apk add binutils libc-dev
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn pymysql


COPY app app
COPY migrations migrations
COPY microblog.py docker/boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP microblog.py

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]


# FROM python:3.6-alpine

# RUN adduser -D microblog

# WORKDIR /home/microblog

# COPY app app
# RUN ls
# COPY migrations migrations
# COPY requirements requirements
# COPY requirements.txt microblog.py boot.sh ./

# RUN python -m venv venv
# ENV FLASK_APP microblog.py
# RUN -m venv/bin/pip3 install -r requirements.txt

# # RUN apk add binutils libc-dev
# # RUN venv/bin/pip install gunicorn pymysql

# # COPY microblog.py docker/boot.sh ./
# RUN chmod +x boot.sh

# RUN ls
# RUN chown -R microblog:microblog ./
# USER microblog

# EXPOSE 5000
# ENTRYPOINT ["./boot.sh"]