---
- name: Creates directory
  file:
    path: /etc/prometheus
    state: directory

- name: Extract Downloaded Node Exporter
  unarchive:
    src: "{{ prometheus }}"
    dest: /etc/prometheus
    remote_src: yes

- name: Copy yml to /etc/prometheus
  template:
    src: config/prometheus.yml
    dest: /etc/prometheus/prometheus-2.10.0.linux-amd64/prometheus.yml


## DENNA STARTAS FORTFARANDE INTE SOM DEN SKA !!! PROBLEM !!!!!!
- name: Run
  shell: chdir=/etc/prometheus/prometheus-2.10.0.linux-amd64/ ./prometheus &






