---
- name: Create directory prometheus
  file:
    path: "{{ path }}"
    state: directory

- name: Extract Downloaded Node Exporter
  unarchive:
    src: "{{ prometheus }}"
    dest: "{{ path }}"
    remote_src: yes

- name: Copy yml to /etc/prometheus
  template:
    src: config/prometheus.yml
    dest: "{{ path }}"/prometheus-2.10.0.linux-amd64/prometheus.yml

# Doesnt work have to go in manually to run prometheus
- name: Enter dir and run prometheus in the background
  shell: chdir="{{ path }}"/prometheus-2.10.0.linux-amd64/ sudo ./prometheus &






