---
-   hosts:
        -   loadBalancer
    remote_user: deploy
    become: true
    become_method: sudo
    roles:
        -   docker_system
        -   load_balancer
        -   nginx_prometheus_exporter