---
-   import_playbook: mysqld_exporter.yml
-   hosts:
        -   monitoringServer
    remote_user: deploy
    become: true
    become_method: sudo
    roles:
        -   monitoring
        -   prometheus
        -   grafana